#!/bin/bash
REV=$1

echo $REV > public/version

echo "[Escualo::Office] Copying robots.txt"
sed -i -e "s/<MUMUKI_BASE_URL>/$MUMUKI_BASE_URL/g" public/robots.production.txt
mv public/robots.production.txt public/robots.txt

echo "[Escualo::Office] Running Migrations..."
rake db:migrate

echo "[Escualo::Office] Compiling assets..."
rake assets:precompile
