#!/bin/bash

echo "[Escualo::Office] Checking DB exists..."
rake db:version > /dev/null 2>&1

if [  $? -eq 0 ]; then
  echo "[Escualo::Office] DB Already exists"
else
  echo "[Escualo::Office] Creating DB..."
  rake db:create db:schema:load db:seed
fi
